# Generated by Django 5.2 on 2025-04-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_status_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, choices=[('dhl', 'DHL'), ('fedex', 'FedEx'), ('ups', 'UPS'), ('usps', 'USPS'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
